- name: adding nginx signing key
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"
    state: present

- name: adding sources.list deb url for nginx
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
    state: present

- name: update the cache and install nginx server
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: updating customized templates for nginx configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"

  with_items:
    - { src: "templates/defautlt.conf.j2", dst: "/etc/nginx/conf.d/default.conf" }

  notify:
    - start nginx
    - startup nginx
