- name: installing docker on ubuntu
  hosts: zap
  remote_user: ubuntu
  gather_facts: no
  become: yes
  vars:
    apt_repo_data: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    apt_gpg_key: https://download.docker.com/linux/ubuntu/gpg

  tasks:
    - name: adding docker gpg key
      apt_key:
        url: "{{ apt_gpg_key }}"
        state: present
      
    - name: add docker repository
      apt_repository:
        repo: "{{ apt_repo_data }}"
        state: present

    - name: installing docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: install python-pip
      apt:
        name: python-pip
        state: present

    - name: install docker-py
      pip:
        name: "{{ item }}"
        state: present
      
      with_items:
        - docker-py
        - docker
